image: alpine/edge
packages:
  - nodejs
  - npm
  - rsync
sources:
  - https://git.sr.ht/~jshsj/jshsj-v2
  - git@git.sr.ht:~jshsj/Flow
secrets:
  - 1fb7cf75-d90f-4df5-9cad-233d4559a311
  - 43473a2b-32b2-4c49-9f79-cebf8e61cf87
  - 010adfa9-eb74-4df4-aa27-4d69305d77d0
tasks:
  - create-dirs: |
      cd jshsj-v2
      mkdir -p src/content/Projekte
      mkdir -p src/content/Blog
      mkdir -p src/content/DigitalGarden
      mkdir -p public/assets/attachments
  - copy-files: |
      mv Flow/flow/Projekte/attachments/* jshsj-v2/public/assets/attachments/
      mv Flow/flow/Blog/attachments/* jshsj-v2/public/assets/attachments/
      mv Flow/flow/DigitalGarden/attachments/* jshsj-v2/public/assets/attachments/
      mv Flow/flow/Projekte/*.md jshsj-v2/src/content/Projekte/
      mv Flow/flow/Blog/*.md jshsj-v2/src/content/Blog/
      mv Flow/flow/DigitalGarden/**/*.md jshsj-v2/src/content/DigitalGarden/

  - setup: |
      cd jshsj-v2
      npm install
  - build: |
      cd jshsj-v2
      npm run build
  - deploy: |
      cd jshsj-v2
      sshopts="ssh -o StrictHostKeyChecking=no"
      set +x
      source ~/.ssh_deploy
      rsync --rsh="$sshopts" -avtPz --delete dist/ $DEPLOY/joshuastuebner.com/
      set -x
