name: Build and deploy
on:
  push:
    branches: [master]
  workflow_dispatch:


jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: JSHSJ/flow
          path: content
          token: ${{ secrets.REPO_PAT }}
      - name: Install lftp
        run: sudo apt install lftp
      - run: mkdir -p src/content/Projekte
      - run: mkdir -p public/assets/attachments
      - run: mv content/flow/Projekte/attachments/* public/assets/attachments/
      - run: mv content/flow/Projekte/*.md src/content/Projekte/
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm run-script build
      - name: Deploy to FTP
        run: lftp -e "open ${{ secrets.FTP_USERNAME }}.kasserver.com; user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}; mirror -X .* -X .*/ --reverse --verbose --delete ./dist/ /joshuastuebner.com/; bye"
