name: Build and deploy
on:
  push:
    branches: [master]
  workflow_dispatch:


jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: JSHSJ/flow
          path: content
          token: ${{ secrets.REPO_PAT }}
      - name: Install lftp
        run: sudo apt install lftp
      - run: mkdir -p src/content/Projekte
      - run: mkdir -p src/content/Blog
      - run: mkdir -p public/assets/attachments
      - run: mv content/flow/Projekte/attachments/* public/assets/attachments/
      - run: mv content/flow/Blog/attachments/* public/assets/attachments/
      - run: mv content/flow/Projekte/*.md src/content/Projekte/
      - run: mv content/flow/Blog/*.md src/content/Blog/
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
            node-version: ${{ matrix.node-version }}
      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.7.js | node - add --global pnpm@6
      - run: pnpm install
      - run: |
        pnpm build
        touch ./dist/.nojekyll
      - name: Deploy to FTP
        run: lftp -e "open ${{ secrets.FTP_USERNAME }}.kasserver.com; user ${{ secrets.FTP_USERNAME }} ${{ secrets.FTP_PASSWORD }}; mirror -X .* -X .*/ --reverse --verbose --delete ./dist/ /joshuastuebner.com/; bye"
